# Generated by Django 3.0.6 on 2023-02-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAlmacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='registroActivo',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AddField(
            model_name='existencia',
            name='registroActivo',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
    ]
