# Generated by Django 3.0.6 on 2023-02-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nombre Producto')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Descripcion Producto')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Precio Producto')),
            ],
        ),
    ]
