# Generated by Django 3.0.6 on 2023-02-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProducto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='registroActivo',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
    ]
