# Generated by Django 3.0.6 on 2023-02-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nombre Cliente')),
                ('direccion', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Direccion Cliente')),
                ('telefono', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Telefono cliente')),
            ],
        ),
    ]
