# Generated by Django 3.0.6 on 2023-02-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Apellidos del Cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nombres del Cliente'),
        ),
    ]
