# Generated by Django 3.0.6 on 2023-02-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCliente', '0002_auto_20230227_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='registroActivo',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
    ]
